export const brands = [
  { name: "Shell", logo: "/logos/shell.svg" },
  { name: "Mobil", logo: "/logos/mobil.svg" },
  { name: "CAT", logo: "/logos/cat.svg" },
  { name: "Castrol", logo: "/logos/castrol.svg" },
  { name: "Ingersoll Rand", logo: "/logos/ingersoll-rand.svg" },
  { name: "Atlas Copco", logo: "/logos/atlas-copco.svg" },
  { name: "KSB", logo: "/logos/ksb.svg" },
  { name: "Parker", logo: "/logos/parker.svg" },
  { name: "Siemens", logo: "/logos/siemens.svg" },
  { name: "Burkert", logo: "/logos/burkert.svg" },
  { name: "Danfoss", logo: "/logos/danfoss.svg" },
  { name: "Belzona", logo: "/logos/belzona.svg" },
  { name: "NSK", logo: "/logos/nsk.svg" },
  { name: "ESAB", logo: "/logos/esab.svg" },
  { name: "3M", logo: "/logos/3m.svg" },
  { name: "Scania", logo: "/logos/scania.svg" },
  { name: "Johnson Controls", logo: "/logos/johnson-controls.svg" },
  { name: "Metos Kitchen Intelligence", logo: "/logos/metos.svg" },
];